### ISSUE TITLE
Migrate to Material Design

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#10]
Although I like the old traditional android design, don't you think that it would be awesome to play with Material design?

**Comment by ezisazis** [comment]
A nice tool for checking/measuring grids: https://play.google.com/store/apps/details?id=com.actinarium.materialcue

**Comment by sionleroux** [comment]
I like this idea, the app is currently lightweight but ugly. To get this going, what's a good place to start?

**Comment by ezisazis** [comment]
Since there are not so many UI elements in the app I can only come up with updating the current ones:
- http://www.materialdoc.com/edit-text/
- https://material.io/guidelines/components/buttons.html#buttons-style

and also adding at least a toolbar:
- http://www.materialdoc.com/toolbars/

+1 don't forget the metrics & keylines
- https://material.io/guidelines/layout/metrics-keylines.html#metrics-keylines-keylines-spacing

**Comment by sionleroux** [comment]
Looks good. Not sure if there's any point in a toolbar though, since we don't actually have any tools...

**Comment by ezisazis** [comment]
Yeah but it's like a must-have for all android apps

**Comment by sionleroux** [comment]
I know but that's silly. We don't even have anything to put there and it would be lame if it's empty. Can't we do something else with that space?

**Comment by ezisazis** [comment]
At least we can show the app's name there as now, but with the new design element

**Comment by sionleroux** [comment]
Seriously I always wanted to remove that blue thing since the very beginning because it was annoying and distracting but never got round to reading the docs on how to do it.

**Comment by sionleroux** [comment]
Before and after pic:
![guess-the-animal-redesign](https://user-images.githubusercontent.com/840466/32596428-8e94e704-c533-11e7-8411-69027822913d.png)

**Comment by ezisazis** [comment]
so much better!
