### ISSUE TITLE
Add new .gitignore

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#11]
Use a well generated .gitignore file instead of the old one:
https://www.gitignore.io/api/android%2Candroidstudio

**Comment by sionleroux** [comment]
IIRC the old one was also generated. When this project uses more modern stuff this will definitely be useful but I am against including personal preference stuff like your favourite editor in project-specific gitignore files (e.g. .intellij directory), those should go in your global gitignore file.

**Comment by ezisazis** [comment]
If you need to ignore other things not-specific to
the project, like your favourite IDE's swap files or configurations then
use your global ignores file for that.

@sinisterstuf maybe you should mention this in the README.MD

**Comment by sionleroux** [comment]
If you still have IntelliJ-related files showing up in git you can add them to a global ignores file, like this:

```
git config --global core.excludesfile '~/.cvsignore'
echo -e '\n; intelliJ\n/.idea/\n*.iml' >> ~/.cvsignore
```

and then they'll be ignored for all repos. :bowing_man:

**Comment by sionleroux** [comment]
Idea from tpope's [pathogen](https://github.com/tpope/vim-pathogen#faq).
