### ISSUE TITLE
Integrate Fabric into the application

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#16]
It comes with lots of nice features:

1. Answers - Real-time analytics and event tracking
2. Beta - App distribution for beta testing
3. Crashlytics - Best-in-class crash reporting
4. Digits - Phone number sign-in
5. Twitter Kit - Twitter login and content

https://docs.fabric.io/android/fabric/overview.html

**Comment by sionleroux** [comment]
I think this is taking things too far...

**Comment by ezisazis** [comment]
TBH I would only use the crashlytics part of it. Whenever the app crashes there will be a new ticket on fabric. Would be great when you want to test it with other ppl too.

**Comment by sionleroux** [comment]
I think we can just use the crash reports provided by Google Play, it'll serve our needs fine. Since that's the only really useful feature on this list I'll consider this closed, but feel free to re-open if another related idea comes up.

**Comment by ezisazis** [comment]
Yeah I think later on when it's going to be hyped AF we can implement Fabric.
