### ISSUE TITLE
Consider the following best practices

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#18]
- [ ] Dagger2 for DI: https://google.github.io/dagger/
- [ ] Reactive programming : https://github.com/ReactiveX/RxJava // https://github.com/ReactiveX/RxKotlin 
- [ ] View Annotations: http://jakewharton.github.io/butterknife/

**Comment by sionleroux** [comment]
I think any of these would be overkill for a project of this small size, but I'm not super familiar with them, so I'm open if you'd like to convince me otherwise.

**Comment by ezisazis** [comment]
Yeah maybe the first two are overkill but the last one is just a tool which saves you time, so you don't have to write (TextView)view.findViewById..... but with a refactor (not-so) later on I will put it into the code
