### ISSUE TITLE
Question: Use static imports or not.

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#35]
There are lots of positive and negative points on using static imports inside your codebase.
@sinisterstuf  I'm curious about your opinion. 

https://en.wikipedia.org/wiki/Static_import

IMHO there are places where It's useful to use, like when you want to set a UI element's visibility, because everyone knows that there are 3 posibilites
- View.Visible
- View.Invisible
- View.Gone

So It's okay to leave out the View part, but all the codes that are made of us and not part of the Android/Java SDK is readable if we keep the class annotation.

**Comment by sionleroux** [comment]
I don't think this is a [Good Thing](http://wiki.c2.com/?GoodThing). What if you have something else, e.g. a button that can also be visible. This might save typing but not as much typing as it'll cause when the code won't compile because you've got clashing names. Let's keep it namespaced.

**Comment by ezisazis** [comment]
@sinisterstuf agree!
