### ISSUE TITLE
Can't see error message on the edittext

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#42]
Emulator: Nexus 5x

<img width="328" alt="screen shot 2017-08-31 at 10 00 39" src="https://user-images.githubusercontent.com/1537077/29967288-3a82d6a6-8f16-11e7-90ca-e87add628987.png">

**Comment by sionleroux** [comment]
My emulator doesn't work and this worked fine on my really old Samsung phone, so I can't really reproduce this. One thing I can think of is that I saw 2 different things you do to show an error on input fields, I used only `userInput.setError()` but maybe the other one (don't remember what it is) is what you need for this phone?

**Comment by ezisazis** [comment]
Usually it's a styles(.xml) issue. Anyway I have to investigate it first, because it's not an obvious issue.

**Comment by sionleroux** [comment]
Hmmm woops I forgot about this issue. You can test it on real phones now in Alpha v0.0.2. 😱

**Comment by sionleroux** [comment]
Real device, real problems:
![screenshot_20171107-005326](https://user-images.githubusercontent.com/840466/32470241-fc3503ae-c356-11e7-873e-4d4e0007a618.png)
any ideas?! 🤔

**Comment by ezisazis** [comment]
I will look at it later today.

**Comment by sionleroux** [comment]
I think I know what the problem is: If you squint _really_ hard you can see that the text _is_ there but it's white on a white background, and that's why you can't read it.

**Comment by ezisazis** [comment]
TBH that was clear from the beginning, it's just some styling issue

**Comment by sionleroux** [comment]
Wasn't clear for me. I thought the text was missing for some reason other than that the colour is simply wrong. I will set the colour explicitly.

**Comment by sionleroux** [comment]
Oh well, I give up struggling against Android Studio. I tried fixing this in cf6f1ed but can't see if it did anything because my emulator won't start and my USB ports apparently don't work. @ezisazis could you check it?

**Comment by sionleroux** [comment]
Hmmm... never mind, that wouldn't work, it sets the field text colour, not the error text colour. I guess one part of the problem is the current theme sucks... 🤔

**Comment by sionleroux** [comment]
In which case it is probably related to #10

**Comment by sionleroux** [comment]
Obligatory screenshot:
<img src="https://user-images.githubusercontent.com/840466/32596172-ac596086-c532-11e7-8f28-e2ddc940fed5.png" width="300px">
Much more readable! 😉
