### ISSUE TITLE
You can skip the screens where you have to type into the input fields

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#5]
Whenever the application can't guess the animal and asks the user what he or she thinks of the user can leave edittext empty and navigate to the next screen.

Affected screens:
- "I give up! What animal are you thinking of?"
- "Oh, I've never heard of _placeholder_ before ..."

**Comment by sionleroux** [comment]
This would be solved by checking the field contains text when the user taps the button, so they won't be allowed to continue without entering text.
