### ISSUE TITLE
Consider using Project boards

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#7]
further information: https://help.github.com/articles/about-project-boards/

Would be nice to track issues.

**Comment by sionleroux** [comment]
Good idea. Not so many issues yet that it would be hard to track, but I see you're working on that :laughing:

**Comment by sionleroux** [comment]
Done! :white_check_mark: behold: https://github.com/sinisterstuf/GuessTheAnimal/projects
