### ISSUE TITLE
Update basics project settings

### ISSUE THREAD

**Issue by ezisazis** [sinisterstuf/GuessTheAnimal#9]
I know you tried to aim the lowest android devices, but I think it would be nice to update the project to:

- [x] at least minSdkVersion: 16
- [x] supportLibraryVersion = "25.3.1"
- [x] com.android.tools.build:gradle:2.3.3
- [ ] kotlin lang

**Comment by sionleroux** [comment]
If we bump up the minSdkVersion so much then this wouldn't work on my Samsung Galaxy Gio which has SDK version 8...

**Comment by ezisazis** [comment]
You have to move on :D

**Comment by sionleroux** [comment]
If I can get a phone with a higher SDK version then maybe, otherwise this'll be pretty tough to test...

**Comment by ezisazis** [comment]
There are lots of good simulators as the build-in one in Android Studio or Genymotion...

**Comment by sionleroux** [comment]
Bumped the SDK versions, support lib etc in 82ee376, feel free to do a pull request if there's anything I missed :wink:
